name: YT-AT
on:
  push:
    paths:
      - 'Lang/**'
      - '.github/**'
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Example: 18.15.40'
        required: false
        default: 'Auto'
      DEVICE:
        description: 'Select device'
        required: false
        default: 'arm64-v8a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64


jobs:
  build1:
    name: 'Buid arm64 root...'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: See build...
        run: |
          # kakathic
          . .github/install.sh
          . .github/Tai-Tool.sh
          . .github/YT.sh





  build2:
    name: 'YouTube...'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Show log build...
        run: |
          # kakathic
          . .github/install.sh
          . .github/Tai-Tool.sh
          . .github/YT.sh
